language: python
python:
  - "2.7"
services:
  - postgresql
addons:
  postgresql: "9.3"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database avia;' -U postgres
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
script:
  - python manage.py test
