language: python
python:
  - "2.7"
services:
  - postgresql

env:
  - DATABASE_URL='postgres://postgres:@localhost:5432/avia' SECRET_KEY='1*8-*#h_ym2(e=&_6&j7q+f753fp3ud$a346%1y)rh_k8beu^i'
addons:
  postgresql: "9.3"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database avia;' -U postgres
  - python manage.py migrate --noinput
script:
  - python manage.py test
